### PR TITLE
add newline to values.py

### LINKED ISSUE #12: values.py doesn't have a newline at the end
At the moment the version updater removes the newline at the end of the file, making style checks fail.

### PR DESCRIPTION
**Pull request by percygautam**
fix #12

### CODE REVIEW

**Comment by percygautam** [comment]
@TAG-Epic  Ready to merge!

**Comment by TAG-Epic** [comment]
[The version generator](https://github.com/TAG-Epic/speedcord/blob/master/.github/tools/update_version.py) would overwrite this. The issue was about fixing the version generator, not editing values.py.

**Comment by percygautam** [comment]
Okay I understand

**Comment by TAG-Epic** [comment]
Are you fixing the version generator or do you want me to unassign you?

**Pull request closed without merging**
