### PR TITLE
exclude garbage files from setup

### LINKED ISSUE #5: Make setup.py not include garbage files
There's a lot of unused files in the output build which increases the size of the library.

Files which should be included
setup.py
speedcord/*
README.md

### PR DESCRIPTION
**Pull request by aitorres**
This PR adds the following list of patterns explicitly to the `find_packages` call during setup, in order to exclude unnecessary files from the packaged build:

- setup.py
- speedcord/*
- README.md

This PR closes #5

### CODE REVIEW

**Comment by TAG-Epic** [comment]
Thanks for the pr! I will look into this tomorrow

**Comment by TAG-Epic** [comment]
This does not seem to be working. All files are still included.

**Comment by aitorres** [comment]
@TAG-Epic I'll check it out later today and try to fix it, will keep you updatedo on that

**Comment by TAG-Epic** [comment]
`find_packages` shouldn't be the problem. The problem is setuptools-git. Maybe just remove the package from install_requires and use [MANIFEST.in](https://packaging.python.org/guides/using-manifest-in/) instead?

**Comment by TAG-Epic** [comment]
I will close this pr for now, if you fix it please make a new PR.

**Pull request closed without merging**
